[package]
name = "musiz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
audiotags = "0.4.1"
rodio = "0.17.3"
tokio = { version = "1.35.1", features = ["time", "full"] }
